// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijowflrebmdromxbugnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlqb3dmbHJlYm1kcm9teGJ1Z25kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NjE2MDEsImV4cCI6MjA1ODMzNzYwMX0.oVYC34SFFKAL4yp58Z1XKQx7hSOPtfjVXtxdd4gx0co";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);