// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqetjywqaxywucpnxivl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxZXRqeXdxYXh5d3VjcG54aXZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MzgxMTcsImV4cCI6MjA1ODUxNDExN30.VwlwnxkLMFj7T74900D8_b_yF77PZCb8rr4W5_OI99A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);